# Dev Logging
logging.level.root=INFO
logging.level.com.example.addressbook=DEBUG

# Show SQL (future use)
spring.jpa.show-sql=true

# Console logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n